services:
  pizzashop:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: pizzashop
    container_name: pizzashop
    environment:
      NODE_ENV: production
      JWT_SECRET: super-secret-string-for-production
      PORT: 3000
      SQLITE_DB_NAME: production.sqlite
      PASSWORD_SALT_ROUNDS: 10
    restart: on-failure
    ports:
      - 80:3000
    healthcheck:
      test: wget --spider http://localhost:3000/health || exit 1
      start_period: 30s
      retries: 15
